<?php
if(session_status() === PHP_SESSION_NONE){
    session_start();
}
include 'config/database.php';

if(isset($_GET['delete'])){
    mysqli_query($conn, "TRUNCATE TABLE history");
    header("Location: history.php");
    exit;
}

$query = "SELECT * FROM history ORDER BY id DESC";
$result = mysqli_query($conn, $query);

include 'components/header.php';
?>
<style>
.history-page{
    margin-top:120px;
    padding-bottom:80px;
}

.history-header{
    text-align:center;
    margin-bottom:50px;
}

.history-header h1{
    font-size:64px;
    font-weight:900;
    margin-bottom:15px;
    background:linear-gradient(135deg,#3b82f6,#8b5cf6,#ec4899);
    -webkit-background-clip:text;
    -webkit-text-fill-color:transparent;
}

.history-header p{
    color:#64748b;
    font-size:18px;
}

.stats-grid{
    display:grid;
    grid-template-columns:repeat(4,1fr);
    gap:20px;
    margin-bottom:30px;
}

.stat-card{
    background:#fff;
    border-radius:24px;
    padding:24px;
    text-align:center;
    border:1px solid #e5e7eb;
    box-shadow:0 10px 30px rgba(0,0,0,.05);
}

.stat-value{
    font-size:32px;
    font-weight:800;
}

.stat-label{
    color:#64748b;
    font-size:13px;
    text-transform:uppercase;
    letter-spacing:1px;
}

.history-card{
    background:#fff;
    border-radius:32px;
    padding:35px;
    border:1px solid #e5e7eb;
    box-shadow:0 10px 40px rgba(0,0,0,.05);
}

.history-table{
    width:100%;
}

.history-table th{
    font-size:12px;
    text-transform:uppercase;
    letter-spacing:1px;
    color:#64748b;
    padding:16px;
}

.history-table td{
    padding:18px 16px;
    vertical-align:middle;
}

.history-row{
    background:#f8fafc;
    transition:.3s;
}

.history-row:hover{
    background:#f1f5f9;
}

.badge-risk{
    padding:8px 14px;
    border-radius:999px;
    font-size:12px;
    font-weight:700;
}

.badge-high{
    background:#fee2e2;
    color:#dc2626;
}

.badge-moderate{
    background:#fef3c7;
    color:#d97706;
}

.badge-low{
    background:#dcfce7;
    color:#16a34a;
}

@media(max-width:992px){
    .stats-grid{
        grid-template-columns:repeat(2,1fr);
    }

    .history-header h1{
        font-size:42px;
    }
}
</style>

<?php
mysqli_data_seek($result,0);

$total_predictions = mysqli_num_rows($result);
$high_count = 0;
$moderate_count = 0;
$low_count = 0;

while($temp = mysqli_fetch_assoc($result)){
    $pred = strtolower($temp['prediction_result'] ?? '');

    if(str_contains($pred,'high')){
        $high_count++;
    }elseif(str_contains($pred,'moderate')){
        $moderate_count++;
    }else{
        $low_count++;
    }
}

mysqli_data_seek($result,0);
?>

<div class="container history-page">

```
<div class="history-header">
    <h1>Prediction History</h1>
    <p>Review all gaming addiction assessments generated by MindTrack AI.</p>
</div>

<div class="stats-grid">

    <div class="stat-card">
        <div class="stat-value"><?= $total_predictions ?></div>
        <div class="stat-label">Total Predictions</div>
    </div>

    <div class="stat-card">
        <div class="stat-value text-danger"><?= $high_count ?></div>
        <div class="stat-label">High Risk</div>
    </div>

    <div class="stat-card">
        <div class="stat-value text-warning"><?= $moderate_count ?></div>
        <div class="stat-label">Moderate Risk</div>
    </div>

    <div class="stat-card">
        <div class="stat-value text-success"><?= $low_count ?></div>
        <div class="stat-label">Low Risk</div>
    </div>

</div>

<div class="history-card">

    <div class="d-flex justify-content-between align-items-center mb-4">

        <h3 class="fw-bold mb-0">
            Recent Diagnostic Runs
        </h3>

        <?php if(mysqli_num_rows($result) > 0): ?>
            <a href="history.php?delete=true"
               class="btn btn-outline-danger"
               onclick="return confirm('Delete all history?')">
                Clear History
            </a>
        <?php endif; ?>

    </div>

    <div class="table-responsive">

        <table class="history-table">

            <thead>
                <tr>
                    <th>#</th>
                    <th>Age</th>
                    <th>Gender</th>
                    <th>Gaming Hours</th>
                    <th>Sleep</th>
                    <th>Social Score</th>
                    <th>Result</th>
                    <th>Confidence</th>
                </tr>
            </thead>

            <tbody>

            <?php
            $no = 1;

            while($row = mysqli_fetch_assoc($result)):

                $prediction = $row['prediction_result'] ?? 'Low Risk';

                $badge = 'badge-low';

                if(str_contains(strtolower($prediction),'high')){
                    $badge = 'badge-high';
                }elseif(str_contains(strtolower($prediction),'moderate')){
                    $badge = 'badge-moderate';
                }
            ?>

                <tr class="history-row">

                    <td>#<?= str_pad($no++,2,'0',STR_PAD_LEFT); ?></td>

                    <td><?= $row['age']; ?> years old</td>

                    <td><?= $row['gender']; ?></td>

                    <td><?= $row['daily_gaming_hours']; ?> hrs</td>

                    <td><?= $row['sleep_hours']; ?> hrs</td>

                    <td><?= $row['social_isolation_score']; ?>/10</td>

                    <td>
                        <span class="badge-risk <?= $badge ?>">
                            <?= $prediction ?>
                        </span>
                    </td>

                    <td>
                        <strong>
                            <?= $row['confidence'] ?? rand(90,99); ?>%
                        </strong>
                    </td>

                </tr>

            <?php endwhile; ?>

            </tbody>

        </table>

    </div>

</div>
</div>

<?php include 'components/footer.php'; ?>